/**
 * Comprehensive Roster Diagnostics Panel
 * 
 * Displays pattern adherence, WTD compliance, and rest period violations
 * for rosters generated by the Atlas engine
 */

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { CheckCircle2, AlertTriangle, Clock, TrendingUp } from "lucide-react";
import type { RosterDiagnostics } from "@/engine/generateRoster";

interface RosterDiagnosticsPanelProps {
  diagnostics: RosterDiagnostics;
}

export function RosterDiagnosticsPanel({ diagnostics }: RosterDiagnosticsPanelProps) {
  const { 
    restViolations, 
    weeklyAverageCompliant, 
    avgHoursPerWeek, 
    staffSummary, 
    overallCompliance,
    autoApplied 
  } = diagnostics;

  const totalViolations = Object.values(restViolations).reduce(
    (sum, violations) => sum + violations.length, 
    0
  );
  const compliantStaff = Object.values(weeklyAverageCompliant).filter(c => c).length;
  const totalStaff = Object.keys(weeklyAverageCompliant).length;

  return (
    <div className="space-y-6">
      {/* Auto-Applied Corrections Alert */}
      {autoApplied && autoApplied.length > 0 && (
        <Alert className="border-blue-200 bg-blue-50">
          <CheckCircle2 className="h-4 w-4 text-blue-600" />
          <AlertDescription>
            <strong>✓ Automatic Corrections Applied:</strong> {autoApplied.length} shift(s) automatically adjusted during generation to resolve rest period violations.
            <details className="mt-2">
              <summary className="cursor-pointer text-sm font-medium text-blue-700 hover:text-blue-800">
                View Applied Corrections
              </summary>
              <div className="mt-2 space-y-1 text-xs">
                {autoApplied.map((c, i) => (
                  <div key={i} className="p-2 bg-white rounded border border-blue-100">
                    <span className="font-semibold">{c.staffName}</span> on <span className="font-mono">{c.date}</span>
                    : Changed <span className="px-1 bg-red-100 text-red-700 rounded">{c.oldShift}</span> to <span className="px-1 bg-green-100 text-green-700 rounded">{c.newShift}</span>
                    <span className="text-muted-foreground ml-1">({c.reason})</span>
                  </div>
                ))}
              </div>
            </details>
          </AlertDescription>
        </Alert>
      )}

      {/* Overall Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <TrendingUp className="h-4 w-4" />
              Pattern Compliance
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between">
              <div className="text-2xl font-bold">
                {overallCompliance.avgCompliance}%
              </div>
              {overallCompliance.avgCompliance === 100 ? (
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-yellow-500" />
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              {overallCompliance.fullyCompliant} of {staffSummary.length} staff fully compliant
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Clock className="h-4 w-4" />
              WTD Compliance
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between">
              <div className="text-2xl font-bold">
                {compliantStaff}/{totalStaff}
              </div>
              {compliantStaff === totalStaff ? (
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-yellow-500" />
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Staff meeting 48h/week average
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <AlertTriangle className="h-4 w-4" />
              Rest Violations
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between">
              <div className="text-2xl font-bold">{totalViolations}</div>
              {totalViolations === 0 ? (
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-red-500" />
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Shifts with &lt;11h rest gaps
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Rest Violations Alert */}
      {totalViolations > 0 && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>
            <strong>⚠️ WTD Rest Period Violations Detected:</strong> {totalViolations} instances where 
            consecutive shifts have less than 11 hours rest between them.
          </AlertDescription>
        </Alert>
      )}

      {/* Staff Details Table */}
      <Card>
        <CardHeader>
          <CardTitle>Staff Compliance Details</CardTitle>
          <CardDescription>
            Pattern adherence and Working Time Directive compliance per staff member
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b bg-muted/50">
                  <th className="p-3 text-left font-medium">Staff ID</th>
                  <th className="p-3 text-center font-medium">Total Shifts</th>
                  <th className="p-3 text-center font-medium">Pattern Match</th>
                  <th className="p-3 text-center font-medium">Avg Hours/Week</th>
                  <th className="p-3 text-center font-medium">Rest Violations</th>
                  <th className="p-3 text-center font-medium">WTD Status</th>
                </tr>
              </thead>
              <tbody>
                {staffSummary.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="p-4 text-center text-muted-foreground">
                      No staff data available
                    </td>
                  </tr>
                ) : (
                  staffSummary.map((staff) => {
                    const violations = restViolations[staff.staffId] || [];
                    const wtdCompliant = weeklyAverageCompliant[staff.staffId] ?? true;
                    const avgHours = avgHoursPerWeek[staff.staffId] ?? 0;

                    return (
                      <tr key={staff.staffId} className="border-b last:border-0 hover:bg-muted/50">
                        <td className="p-3 font-mono text-xs">
                          {staff.staffName || staff.staffId.slice(0, 8)}...
                        </td>
                        <td className="p-3 text-center">{staff.totalShifts}</td>
                        <td className="p-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <span className="font-semibold">{staff.patternCompliance}%</span>
                            {staff.patternCompliance === 100 ? (
                              <CheckCircle2 className="h-4 w-4 text-green-500" />
                            ) : staff.patternCompliance >= 80 ? (
                              <AlertTriangle className="h-4 w-4 text-yellow-500" />
                            ) : (
                              <AlertTriangle className="h-4 w-4 text-red-500" />
                            )}
                          </div>
                        </td>
                        <td className="p-3 text-center">
                          <div className="flex items-center justify-center gap-1">
                            <Clock className="h-3 w-3 text-muted-foreground" />
                            <span>{avgHours.toFixed(1)}h</span>
                          </div>
                        </td>
                        <td className="p-3 text-center">
                          {violations.length === 0 ? (
                            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                              None
                            </Badge>
                          ) : (
                            <Badge variant="destructive">{violations.length}</Badge>
                          )}
                        </td>
                        <td className="p-3 text-center">
                          {wtdCompliant ? (
                            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                              ✓ Compliant
                            </Badge>
                          ) : (
                            <Badge variant="destructive">⚠ Over 48h</Badge>
                          )}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Detailed Violations Section */}
          {totalViolations > 0 && (
            <div className="mt-6 space-y-3">
              <h4 className="text-sm font-semibold flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-red-500" />
                Detailed Rest Period Violations
              </h4>
              <div className="space-y-2 max-h-60 overflow-y-auto">
                {Object.entries(restViolations).map(([staffId, violations]) =>
                  violations.map((violation, idx) => (
                    <div 
                      key={`${staffId}-${idx}`} 
                      className="p-3 bg-red-50 rounded-md text-sm text-red-900 border border-red-200"
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <span className="font-mono font-semibold">{staffId.slice(0, 8)}...</span>
                          <span className="text-red-700"> → </span>
                          <span className="font-medium">{violation.day}</span>
                        </div>
                        <span className="text-xs bg-red-200 px-2 py-1 rounded">
                          {violation.gap.toFixed(1)}h rest
                        </span>
                      </div>
                      <p className="mt-1 text-xs text-red-700">{violation.message}</p>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
