/**
 * Comprehensive Roster Diagnostics Panel
 * 
 * Displays pattern adherence, WTD compliance, and rest period violations
 * for rosters generated by the Atlas engine
 */

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { CheckCircle2, AlertTriangle, Clock, TrendingUp, Lightbulb, Lock } from "lucide-react";
import type { RosterDiagnostics } from "@/engine/generateRoster";
import { Button } from "@/components/ui/button";
import { useState } from "react";

interface RosterDiagnosticsPanelProps {
  diagnostics: RosterDiagnostics;
}

export function RosterDiagnosticsPanel({ diagnostics }: RosterDiagnosticsPanelProps) {
  const { 
    restViolations, 
    weeklyAverageCompliant, 
    avgHoursPerWeek, 
    staffSummary, 
    overallCompliance,
    autoApplied,
    fairnessBalancing,
    patternAdherenceReport,
    patternMode
  } = diagnostics;

  const [showAllAdherence, setShowAllAdherence] = useState(false);

  const totalViolations = Object.values(restViolations).reduce(
    (sum, violations) => sum + violations.length, 
    0
  );
  const compliantStaff = Object.values(weeklyAverageCompliant).filter(c => c).length;
  const totalStaff = Object.keys(weeklyAverageCompliant).length;

  return (
    <div className="space-y-6">
      {/* Auto-Applied Corrections Alert */}
      {autoApplied && autoApplied.length > 0 && (
        <Alert className="border-blue-200 bg-blue-50">
          <CheckCircle2 className="h-4 w-4 text-blue-600" />
          <AlertDescription>
            <strong>✓ Automatic Corrections Applied:</strong> {autoApplied.length} shift(s) automatically adjusted during generation to resolve rest period violations.
            <details className="mt-2">
              <summary className="cursor-pointer text-sm font-medium text-blue-700 hover:text-blue-800">
                View Applied Corrections
              </summary>
              <div className="mt-2 space-y-1 text-xs">
                {autoApplied.map((c, i) => (
                  <div key={i} className="p-2 bg-white rounded border border-blue-100">
                    <span className="font-semibold">{c.staffName}</span> on <span className="font-mono">{c.date}</span>
                    : Changed <span className="px-1 bg-red-100 text-red-700 rounded">{c.oldShift}</span> to <span className="px-1 bg-green-100 text-green-700 rounded">{c.newShift}</span>
                    <span className="text-muted-foreground ml-1">({c.reason})</span>
                  </div>
                ))}
              </div>
            </details>
          </AlertDescription>
        </Alert>
      )}

      {/* AI Fairness Balancing Alert */}
      {fairnessBalancing && fairnessBalancing.appliedCount > 0 && (
        <Alert className="border-purple-200 bg-purple-50">
          <Lightbulb className="h-4 w-4 text-purple-600" />
          <AlertDescription>
            <strong>🤖 AI Fairness Balancing Applied:</strong> {fairnessBalancing.appliedCount} shift(s) adjusted based on historical workload analysis ({fairnessBalancing.historicalDataPoints} past assignments) to prevent staff fatigue and ensure equitable distribution.
          </AlertDescription>
        </Alert>
      )}

      {/* Pattern Adherence Mode Alert */}
      {patternMode === 'locked' && (
        <Alert className="border-blue-200 bg-blue-50">
          <Lock className="h-4 w-4 text-blue-600" />
          <AlertDescription>
            <strong>🔒 Locked Pattern Mode:</strong> Staff assignments strictly follow their assigned patterns. Deviations only occur for WTD rest compliance.
          </AlertDescription>
        </Alert>
      )}

      {/* Overall Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <TrendingUp className="h-4 w-4" />
              Pattern Compliance
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between">
              <div className="text-2xl font-bold">
                {overallCompliance.avgCompliance}%
              </div>
              {overallCompliance.avgCompliance === 100 ? (
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-yellow-500" />
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              {overallCompliance.fullyCompliant} of {staffSummary.length} staff fully compliant
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Clock className="h-4 w-4" />
              WTD Compliance
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between">
              <div className="text-2xl font-bold">
                {compliantStaff}/{totalStaff}
              </div>
              {compliantStaff === totalStaff ? (
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-yellow-500" />
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Staff meeting 48h/week average
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <AlertTriangle className="h-4 w-4" />
              Rest Violations
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between">
              <div className="text-2xl font-bold">{totalViolations}</div>
              {totalViolations === 0 ? (
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-red-500" />
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Shifts with &lt;11h rest gaps
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Pattern Adherence Report Card */}
      {patternAdherenceReport && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <Lock className="h-5 w-5" />
                  Pattern Adherence Report
                </CardTitle>
                <CardDescription>
                  Deviation tracking and pattern compliance analysis
                </CardDescription>
              </div>
              <div className="text-right">
                <div className="text-3xl font-bold">
                  {patternAdherenceReport.overallAdherence.toFixed(1)}%
                </div>
                <p className="text-xs text-muted-foreground">Overall Adherence</p>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Summary Statistics */}
            <div className="grid grid-cols-3 gap-4 p-4 bg-muted/30 rounded-lg">
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">
                  {patternAdherenceReport.restOverrides}
                </div>
                <p className="text-xs text-muted-foreground">Rest Overrides</p>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-amber-600">
                  {patternAdherenceReport.unmetDemandFills}
                </div>
                <p className="text-xs text-muted-foreground">Unmet Demand Fills</p>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-green-600">
                  {patternAdherenceReport.staffDetails.filter(s => s.adherencePercent === 100).length}
                </div>
                <p className="text-xs text-muted-foreground">Perfect Adherence</p>
              </div>
            </div>

            {/* Staff Adherence Table - Worst 5 or All */}
            <div>
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-sm font-semibold">
                  {showAllAdherence ? 'All Staff' : 'Lowest Adherence (Top 5)'}
                </h4>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowAllAdherence(!showAllAdherence)}
                >
                  {showAllAdherence ? 'Show Top 5' : 'View All'}
                </Button>
              </div>
              <div className="rounded-md border">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b bg-muted/50">
                      <th className="p-2 text-left font-medium">Staff</th>
                      <th className="p-2 text-center font-medium">Adherence</th>
                      <th className="p-2 text-center font-medium">Total Days</th>
                      <th className="p-2 text-center font-medium">Deviations</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(showAllAdherence 
                      ? patternAdherenceReport.staffDetails 
                      : patternAdherenceReport.staffDetails.slice(0, 5)
                    ).map((staff) => (
                      <tr key={staff.staffId} className="border-b last:border-0 hover:bg-muted/30">
                        <td className="p-2 font-medium">{staff.staffName}</td>
                        <td className="p-2 text-center">
                          <Badge 
                            variant={staff.adherencePercent === 100 ? "default" : "outline"}
                            className={
                              staff.adherencePercent === 100 ? "bg-green-100 text-green-800" :
                              staff.adherencePercent >= 90 ? "bg-blue-100 text-blue-800" :
                              staff.adherencePercent >= 70 ? "bg-yellow-100 text-yellow-800" :
                              "bg-red-100 text-red-800"
                            }
                          >
                            {staff.adherencePercent.toFixed(1)}%
                          </Badge>
                        </td>
                        <td className="p-2 text-center">{staff.totalDays}</td>
                        <td className="p-2 text-center">
                          {staff.deviations.length > 0 ? (
                            <details className="inline-block">
                              <summary className="cursor-pointer text-xs text-blue-600 hover:underline">
                                {staff.deviations.length} deviations
                              </summary>
                              <div className="mt-2 space-y-1 text-xs p-2 bg-muted/50 rounded">
                                {staff.deviations.slice(0, 5).map((dev, idx) => (
                                  <div key={idx} className="flex items-center gap-2">
                                    <span className="font-mono">{dev.date}</span>
                                    <span className="text-muted-foreground">→</span>
                                    <span className="font-mono text-red-600">{dev.expected}</span>
                                    <span className="text-muted-foreground">to</span>
                                    <span className="font-mono text-green-600">{dev.actual}</span>
                                    <Badge variant="outline" className="text-xs">
                                      {dev.reason.replace(/_/g, ' ')}
                                    </Badge>
                                  </div>
                                ))}
                                {staff.deviations.length > 5 && (
                                  <p className="text-muted-foreground">
                                    ...and {staff.deviations.length - 5} more
                                  </p>
                                )}
                              </div>
                            </details>
                          ) : (
                            <Badge variant="outline" className="bg-green-50 text-green-700">
                              None
                            </Badge>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Rest Violations Alert */}
      {totalViolations > 0 && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>
            <strong>⚠️ WTD Rest Period Violations Detected:</strong> {totalViolations} instances where 
            consecutive shifts have less than 11 hours rest between them.
          </AlertDescription>
        </Alert>
      )}

      {/* Staff Details Table */}
      <Card>
        <CardHeader>
          <CardTitle>Staff Compliance Details</CardTitle>
          <CardDescription>
            Pattern adherence and Working Time Directive compliance per staff member
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b bg-muted/50">
                  <th className="p-3 text-left font-medium">Staff ID</th>
                  <th className="p-3 text-center font-medium">Total Shifts</th>
                  <th className="p-3 text-center font-medium">Pattern Match</th>
                  <th className="p-3 text-center font-medium">Avg Hours/Week</th>
                  <th className="p-3 text-center font-medium">Rest Violations</th>
                  <th className="p-3 text-center font-medium">WTD Status</th>
                </tr>
              </thead>
              <tbody>
                {staffSummary.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="p-4 text-center text-muted-foreground">
                      No staff data available
                    </td>
                  </tr>
                ) : (
                  staffSummary.map((staff) => {
                    const violations = restViolations[staff.staffId] || [];
                    const wtdCompliant = weeklyAverageCompliant[staff.staffId] ?? true;
                    const avgHours = avgHoursPerWeek[staff.staffId] ?? 0;

                    return (
                      <tr key={staff.staffId} className="border-b last:border-0 hover:bg-muted/50">
                        <td className="p-3 font-mono text-xs">
                          {staff.staffName || staff.staffId.slice(0, 8)}...
                        </td>
                        <td className="p-3 text-center">{staff.totalShifts}</td>
                        <td className="p-3 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <span className="font-semibold">{staff.patternCompliance}%</span>
                            {staff.patternCompliance === 100 ? (
                              <CheckCircle2 className="h-4 w-4 text-green-500" />
                            ) : staff.patternCompliance >= 80 ? (
                              <AlertTriangle className="h-4 w-4 text-yellow-500" />
                            ) : (
                              <AlertTriangle className="h-4 w-4 text-red-500" />
                            )}
                          </div>
                        </td>
                        <td className="p-3 text-center">
                          <div className="flex items-center justify-center gap-1">
                            <Clock className="h-3 w-3 text-muted-foreground" />
                            <span>{avgHours.toFixed(1)}h</span>
                          </div>
                        </td>
                        <td className="p-3 text-center">
                          {violations.length === 0 ? (
                            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                              None
                            </Badge>
                          ) : (
                            <Badge variant="destructive">{violations.length}</Badge>
                          )}
                        </td>
                        <td className="p-3 text-center">
                          {wtdCompliant ? (
                            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                              ✓ Compliant
                            </Badge>
                          ) : (
                            <Badge variant="destructive">⚠ Over 48h</Badge>
                          )}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Detailed Violations Section */}
          {totalViolations > 0 && (
            <div className="mt-6 space-y-3">
              <h4 className="text-sm font-semibold flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-red-500" />
                Detailed Rest Period Violations
              </h4>
              <div className="space-y-2 max-h-60 overflow-y-auto">
                {Object.entries(restViolations).map(([staffId, violations]) =>
                  violations.map((violation, idx) => (
                    <div 
                      key={`${staffId}-${idx}`} 
                      className="p-3 bg-red-50 rounded-md text-sm text-red-900 border border-red-200"
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <span className="font-mono font-semibold">{staffId.slice(0, 8)}...</span>
                          <span className="text-red-700"> → </span>
                          <span className="font-medium">{violation.day}</span>
                        </div>
                        <span className="text-xs bg-red-200 px-2 py-1 rounded">
                          {violation.gap.toFixed(1)}h rest
                        </span>
                      </div>
                      <p className="mt-1 text-xs text-red-700">{violation.message}</p>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Performance Metrics Footer */}
      {diagnostics.perfMetrics && (
        <Card className="bg-muted/30">
          <CardContent className="pt-4">
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-2 text-muted-foreground">
                <Clock className="h-4 w-4" />
                <span className="font-medium">Performance Metrics</span>
              </div>
              <div className="flex gap-6 font-mono text-xs">
                <span>
                  Fetch: <span className="font-semibold text-foreground">{diagnostics.perfMetrics.fetchMs}ms</span>
                </span>
                <span>
                  Generate: <span className="font-semibold text-foreground">{diagnostics.perfMetrics.genMs}ms</span>
                </span>
                <span>
                  Insert: <span className="font-semibold text-foreground">{diagnostics.perfMetrics.insertMs}ms</span>
                </span>
                <span className="text-foreground">
                  Total: <span className="font-bold">{diagnostics.perfMetrics.totalMs}ms</span>
                </span>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
