/**
 * Pattern-locked roster generation
 * 
 * When pattern-locked mode is enabled, rosters are generated by:
 * 1. Resolving each staff member's pattern (custom or site default)
 * 2. Expanding patterns across the roster horizon
 * 3. Creating candidate duties only on work days (R = rest stays rest)
 * 4. Matching duties to coverage requirements
 */

import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import type { ShiftCode } from './types';
import { resolvePatternsBatch } from './resolve';
import { expandPatternsBatch } from './expand';
import { applyAbsenceOverlay } from './overlayAbsence';

// ============================================================================
// TYPES
// ============================================================================

/**
 * A candidate duty generated from a pattern
 */
export interface PatternDuty {
  staffId: string;
  date: string;          // YYYY-MM-DD
  shiftCode: ShiftCode;  // D, E, L, N (never R)
  source: 'pattern';     // Mark as pattern-sourced for debugging
}

/**
 * Pattern-locked generation input
 */
export interface PatternLockedInput {
  /** Start date of roster period (YYYY-MM-DD) */
  startDate: string;
  
  /** End date of roster period (YYYY-MM-DD, inclusive) */
  endDate: string;
  
  /** Staff member IDs to generate for */
  staffIds: string[];
  
  /** Tenant ID for pattern resolution */
  tenantId: string;
  
  /** Optional site ID for pattern resolution */
  siteId?: string | null;
  
  /** Shift framework (8h or 12h) */
  framework: '8h' | '12h';
}

/**
 * Pattern-locked generation result
 */
export interface PatternLockedResult {
  /** Candidate duties from patterns */
  duties: PatternDuty[];
  
  /** Staff members with patterns resolved */
  staffWithPatterns: string[];
  
  /** Staff members without patterns (excluded) */
  staffWithoutPatterns: string[];
  
  /** Warnings encountered during generation */
  warnings: string[];
}

// ============================================================================
// FRAMEWORK SHIFT CODE VALIDATION
// ============================================================================

/**
 * Check if a shift code is valid for the given framework
 */
function isValidForFramework(code: ShiftCode, framework: '8h' | '12h'): boolean {
  if (code === 'R') return false; // Rest is never a duty
  
  if (framework === '12h') {
    return code === 'D' || code === 'N'; // Only D and N in 12h
  } else {
    return code === 'E' || code === 'L' || code === 'N'; // E, L, N in 8h
  }
}

/**
 * Remap shift codes for framework compatibility
 * In 12h framework: E/L → D
 */
function remapForFramework(code: ShiftCode, framework: '8h' | '12h'): ShiftCode {
  if (framework === '12h' && (code === 'E' || code === 'L')) {
    console.log(`🔄 Remapping ${code} → D for 12h framework`);
    return 'D';
  }
  return code;
}

// ============================================================================
// PATTERN-LOCKED GENERATION
// ============================================================================

/**
 * Generate candidate duties from staff patterns
 * 
 * This is the primary entry point for pattern-locked roster generation.
 * It resolves patterns, expands them, and creates duties only on work days.
 * 
 * IMPORTANT CONSTRAINTS:
 * - Rest days (R) are NEVER converted to duties
 * - Only generates duties on dates where pattern has D/E/L/N
 * - Remaps E/L → D automatically for 12h framework
 * - Skips staff members without resolved patterns
 * 
 * @param input - Pattern-locked generation input
 * @returns Candidate duties and resolution metadata
 */
export async function generatePatternLockedDuties(
  input: PatternLockedInput
): Promise<PatternLockedResult> {
  console.log('🔒 Starting pattern-locked duty generation:', {
    staffCount: input.staffIds.length,
    dateRange: `${input.startDate} to ${input.endDate}`,
    framework: input.framework,
  });

  const warnings: string[] = [];
  const duties: PatternDuty[] = [];

  // Step 1: Resolve patterns for all staff
  console.log('🎯 Step 1: Resolving patterns for staff members');
  const resolutions = await resolvePatternsBatch(
    input.staffIds,
    input.tenantId,
    input.siteId
  );

  // GUARDRAIL: Block generation if any staff lack patterns
  const staffWithoutPatterns: string[] = [];
  const staffWithPatterns: string[] = [];
  
  for (const staffId of input.staffIds) {
    if (resolutions.has(staffId)) {
      staffWithPatterns.push(staffId);
    } else {
      staffWithoutPatterns.push(staffId);
    }
  }

  if (staffWithoutPatterns.length > 0) {
    console.error('❌ GUARDRAIL: Staff without patterns detected in pattern-locked mode');
    
    // Get staff names for better error messages
    const { data: staffProfiles } = await supabase
      .from('staff_profiles')
      .select('id, first_name, last_name, name')
      .in('id', staffWithoutPatterns.slice(0, 5)); // Limit to 5 for toast

    const missingStaffNames = (staffProfiles || []).map(s => 
      s.name || `${s.first_name || ''} ${s.last_name || ''}`.trim() || s.id
    );

    const displayNames = missingStaffNames.length > 0 
      ? missingStaffNames.join(', ')
      : staffWithoutPatterns.slice(0, 5).join(', ');

    const totalMissing = staffWithoutPatterns.length;
    const additionalCount = totalMissing > 5 ? ` (+${totalMissing - 5} more)` : '';

    toast({
      title: "❌ Generation Blocked: Missing Patterns",
      description: `Pattern-locked mode requires all staff to have assigned patterns. Missing for: ${displayNames}${additionalCount}. Click to manage patterns.`,
      variant: "destructive",
    });

    // Provide link in console for now (toast actions have limited API)
    console.error('🔗 Fix this by assigning patterns at: /patterns');

    return {
      duties: [],
      staffWithPatterns,
      staffWithoutPatterns,
      warnings: [
        'Generation aborted: Pattern-locked mode requires all staff to have patterns',
        ...staffWithoutPatterns.map(id => `Staff ${id} has no pattern assigned`)
      ],
    };
  }

  console.log(`✓ All ${staffWithPatterns.length} staff have patterns - proceeding with generation`);

  // Step 2: Expand patterns over date range
  console.log('📅 Step 2: Expanding patterns over roster horizon');
  const expansions = expandPatternsBatch(
    resolutions,
    input.startDate,
    input.endDate
  );

  console.log(`✓ Expanded patterns for ${expansions.size} staff members`);

  // Step 2.5: Overlay approved absences (blocks pattern duties on leave days)
  console.log('🚫 Step 2.5: Overlaying approved absences');
  const expansionsWithAbsence = await applyAbsenceOverlay(
    expansions,
    input.startDate,
    input.endDate
  );

  console.log(`✓ Applied absence overlay`);

  // Step 3: Convert pattern days to candidate duties
  console.log('🔨 Step 3: Creating candidate duties from patterns');
  let totalDays = 0;
  let workDays = 0;
  let remappedDays = 0;
  let absenceDaysSkipped = 0;

  for (const [staffId, expandedDays] of expansionsWithAbsence.entries()) {
    totalDays += expandedDays.length;

    for (const day of expandedDays) {
      // Skip rest days - they are never duties
      if (day.is_rest) {
        // Track if this is an absence day
        if (day.absence === 'A') {
          absenceDaysSkipped++;
        }
        continue;
      }

      // Remap shift code for framework if needed
      const originalCode = day.shift_code;
      const remappedCode = remapForFramework(originalCode, input.framework);
      
      if (remappedCode !== originalCode) {
        remappedDays++;
      }

      // Validate code is valid for framework after remapping
      if (!isValidForFramework(remappedCode, input.framework)) {
        console.warn(`⚠️ Skipping invalid shift code ${remappedCode} for ${input.framework} framework on ${day.date}`);
        warnings.push(`Invalid shift code ${remappedCode} for staff ${staffId} on ${day.date}`);
        continue;
      }

      // Create duty
      duties.push({
        staffId,
        date: day.date,
        shiftCode: remappedCode,
        source: 'pattern',
      });

      workDays++;
    }
  }

  console.log('✅ Pattern-locked duty generation complete:', {
    totalPatternDays: totalDays,
    workDays,
    restDays: totalDays - workDays,
    absenceDaysBlocked: absenceDaysSkipped,
    dutiesCreated: duties.length,
    remappedCodes: remappedDays,
    staffWithPatterns: staffWithPatterns.length,
    staffWithoutPatterns: staffWithoutPatterns.length,
  });

  if (remappedDays > 0) {
    console.log(`ℹ️ Remapped ${remappedDays} shift codes for ${input.framework} framework compatibility`);
  }

  if (absenceDaysSkipped > 0) {
    console.log(`🚫 Blocked ${absenceDaysSkipped} days due to approved absences`);
  }

  return {
    duties,
    staffWithPatterns,
    staffWithoutPatterns,
    warnings,
  };
}

/**
 * Check if a staff member is available on a given date based on their pattern
 * (Used by generators to check if a date is a rest day)
 */
export function isPatternRestDay(
  staffId: string,
  date: string,
  expansions: Map<string, Array<{ date: string; is_rest: boolean }>>
): boolean {
  const expansion = expansions.get(staffId);
  if (!expansion) return false;

  const dayEntry = expansion.find(d => d.date === date);
  return dayEntry?.is_rest ?? false;
}
